public enum TypeOfThing 
{
    None,                
    Grass,                   
    Stream,                  
    Path,                 
    Rock,                    
    Stone,                   
    Clay,                    
    Ore,                    
    Iron,                    
    BerryBush,               
    Mushroom,                
    Wood,                   
    FallenWood,
    Villager,
    Hen                     ,
    Chick                   ,
    Rooster                 ,
    MudFloor                ,
    MudFloorBlueprint       ,
    StoneFloor              ,
    StoneWall               ,
    WoodFloor               ,
    WoodFloorBlueprint      ,
    SoilFloor               ,
    SoilFloorBlueprint      ,
    CabbageSeed,
    CabbageCrop               ,
    CabbageCropBlueprint      ,
    ForagedWall             ,
    ForagedWallBlueprint    ,
    Fire                    ,
    FireBlueprint           ,
    WoodWall                ,
    WoodWallBlueprint       ,
    StoneFloorBlueprint     ,
    StoneWallBlueprint      ,
    FenceBlueprint          ,
    Fence                   ,
    DoorBlueprint           ,
    Door                    ,
    BedBlueprint            ,
    Bed                     ,
    ForagedBed              ,
    ForagedBedBlueprint     ,
    ClayForge               ,
    ClayForgeBlueprint      ,
    Workbench               ,
    WorkbenchBlueprint      ,
    Axe                     ,
    Hoe                     ,
    Storage                 ,
    StorageBlueprint        ,
    Tree                    ,
}