public enum TypeOfThing 
{
    None,         
    Blueprint,       
    Grass,                   
    Stream,                  
    Path,                 
    Rock,                    
    Stone,                   
    ClayFloor,
    Clay,                    
    Ore,      
    OreFloor,              
    Iron,                    
    BerryBush,               
    MushroomGrowing,   
    Mushroom,         
    Wood,       
    WoodenPlanks,            
    FallenWood,
    Villager,
    Hen                     ,
    Chick                   ,
    Rooster                 ,
    MudFloor                ,
    // MudFloorBlueprint       ,
    StoneFloor              ,
    StoneWall               ,
    WoodFloor               ,
    SoilFloor               ,
    CabbageSeed,
    CabbageCrop               ,
    Cabbage,
    ForagedWall             ,
    Fire                    ,
    WoodWall                ,
    Fence                   ,
    Bucket,
    Table,
    Chair,

    Door                    ,
    Bed                     ,
    ForagedBed              ,
    ClayForge               ,
    Workbench               ,
    CarpentersBench,
    Axe                     ,
    Hoe                     ,
    Storage                 ,
    // StorageBlueprint        ,
    Tree                    ,
}