public enum TypeOfThing 
{
    None,         
    Blueprint,       
    Grass,                   
    Stream,                  
    Path,                 
    Rock,                    
    Stone,                   
    ClayFloor,
    Clay,                    
    Ore,      
    OreFloor,              
    Iron,                    
    BerryBush,               
    MushroomGrowing,   
    Mushroom,         
    Wood,                   
    FallenWood,
    Villager,
    Hen                     ,
    Chick                   ,
    Rooster                 ,
    MudFloor                ,
    // MudFloorBlueprint       ,
    StoneFloor              ,
    StoneWall               ,
    WoodFloor               ,
    // WoodFloorBlueprint      ,
    SoilFloor               ,
    // SoilFloorBlueprint      ,
    CabbageSeed,
    CabbageCrop               ,
    // CabbageCropBlueprint      ,
    ForagedWall             ,
    // ForagedWallBlueprint    ,
    Fire                    ,
    // FireBlueprint           ,
    WoodWall                ,
    // WoodWallBlueprint       ,
    // StoneFloorBlueprint     ,
    // StoneWallBlueprint      ,
    // FenceBlueprint          ,
    Fence                   ,
    // DoorBlueprint           ,
    Door                    ,
    // BedBlueprint            ,
    Bed                     ,
    ForagedBed              ,
    // ForagedBedBlueprint     ,
    ClayForge               ,
    // ClayForgeBlueprint      ,
    Workbench               ,
    // WorkbenchBlueprint      ,
    Axe                     ,
    Hoe                     ,
    Storage                 ,
    // StorageBlueprint        ,
    Tree                    ,
}